//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.05 at 11:20:44 PM EET 
//


package invoice.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the invoice.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: invoice.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link Form.Customer }
     * 
     */
    public Form.Customer createFormCustomer() {
        return new Form.Customer();
    }

    /**
     * Create an instance of {@link Form.Order }
     * 
     */
    public Form.Order createFormOrder() {
        return new Form.Order();
    }

    /**
     * Create an instance of {@link Form.Supplier }
     * 
     */
    public Form.Supplier createFormSupplier() {
        return new Form.Supplier();
    }

    /**
     * Create an instance of {@link Form.Transporter }
     * 
     */
    public Form.Transporter createFormTransporter() {
        return new Form.Transporter();
    }

}
